name: CI/CD to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: speedaf-logistics-system
      REGION: us-central1
      REPO: containers
      SERVICE: speedaf-api
      IMAGE_URI: us-central1-docker.pkg.dev/speedaf-logistics-system/containers/speedaf-api:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Auth Artifact Registry
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev -q

      - name: Build image (Cloud Build)
        run: gcloud builds submit --tag "$IMAGE_URI"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE" \
            --image "$IMAGE_URI" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --min-instances=0 \
            --max-instances=2 \
            --cpu=1 --memory=256Mi --concurrency=80
